"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 6.1.1.

For more information on this file, see
https://docs.djangoproject.com/en/6.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.1/ref/settings/
"""

import os
from pathlib import Path

import environ
from django.contrib.messages import constants as message_constants

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Environment configuration (12-factor).
# Local development works with no .env file: the defaults below are dev-safe.
# Production supplies real values via the environment (or a .env file).
# See .env.example for the full list of supported variables.
env = environ.Env(
    DEBUG=(bool, True),
    ALLOWED_HOSTS=(list, ['localhost', '127.0.0.1']),
)
_env_file = BASE_DIR / '.env'
if _env_file.exists():
    env.read_env(_env_file)

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = env('DEBUG')

# SECURITY WARNING: keep the secret key used in production secret!
# A throwaway key is fine for local development, but production (DEBUG=False)
# must supply its own SECRET_KEY - it never falls back to a shared value.
if DEBUG:
    SECRET_KEY = env(
        'SECRET_KEY',
        default='django-insecure-dev-only-do-not-use-in-production',
    )
else:
    SECRET_KEY = env('SECRET_KEY')

ALLOWED_HOSTS = env('ALLOWED_HOSTS')

# Production HTTPS / secure-cookie settings. Active only when DEBUG is False, so
# local development over plain HTTP is unchanged. TLS is assumed to be
# terminated by a reverse proxy that forwards the X-Forwarded-Proto header.
if not DEBUG:
    SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')
    SECURE_SSL_REDIRECT = env.bool('SECURE_SSL_REDIRECT', default=True)

    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True

    SECURE_HSTS_SECONDS = env.int('SECURE_HSTS_SECONDS', default=3600)
    SECURE_HSTS_INCLUDE_SUBDOMAINS = env.bool(
        'SECURE_HSTS_INCLUDE_SUBDOMAINS', default=True
    )
    SECURE_HSTS_PRELOAD = env.bool('SECURE_HSTS_PRELOAD', default=True)

    # Full origins (scheme + host) allowed to submit forms / use the admin, e.g.
    # CSRF_TRUSTED_ORIGINS=https://example.com,https://www.example.com
    CSRF_TRUSTED_ORIGINS = env.list('CSRF_TRUSTED_ORIGINS', default=[])


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'predictions.apps.PredictionsConfig',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    # WhiteNoise serves collected static files in production; it must sit
    # directly after SecurityMiddleware and before everything else.
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    # Activates the visitor's browser-reported time zone (tz cookie).
    'predictions.middleware.TimezoneMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'predictions.context_processors.user_points',
                'predictions.context_processors.public_nav',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.1/ref/settings/#databases

# SQLite is the default for local development. Set DATABASE_URL to point at
# any other database in production, e.g.
#   DATABASE_URL=postgres://USER:PASSWORD@HOST:PORT/NAME
# which django-environ parses into ENGINE 'django.db.backends.postgresql'
# plus NAME / USER / PASSWORD / HOST / PORT (the psycopg driver is used at
# connection time). No connection is made while settings load.
if 'DATABASE_URL' in os.environ:
    DATABASES = {'default': env.db('DATABASE_URL')}
    # Reuse connections between requests in production. Both are
    # environment-configurable (CONN_MAX_AGE in seconds; 0 disables reuse).
    DATABASES['default']['CONN_MAX_AGE'] = env.int('CONN_MAX_AGE', default=60)
    DATABASES['default']['CONN_HEALTH_CHECKS'] = env.bool(
        'CONN_HEALTH_CHECKS', default=True
    )
else:
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': BASE_DIR / 'db.sqlite3',
        }
    }


# Password validation
# https://docs.djangoproject.com/en/6.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.1/howto/static-files/

STATIC_URL = '/static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'

# Media files (user uploads, e.g. team flags)
# https://docs.djangoproject.com/en/6.1/topics/files/
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

STORAGES = {
    'default': {
        # Uploads (team flags) live in the database: the Railway disk is
        # ephemeral. Served by predictions.views.media_file at /media/.
        'BACKEND': 'predictions.storage.DatabaseStorage',
    },
    'staticfiles': {
        # Production: WhiteNoise compressed + hashed manifest storage.
        # Development: the plain storage, so pages that use {% static %}
        # (the admin) render without first running collectstatic.
        'BACKEND': (
            'django.contrib.staticfiles.storage.StaticFilesStorage'
            if DEBUG
            else 'whitenoise.storage.CompressedManifestStaticFilesStorage'
        ),
    },
}

# Named URL of the login page. @login_required sends guests here.
LOGIN_URL = 'login'
# After a successful login or logout, send the user to the match list.
LOGIN_REDIRECT_URL = 'match_list'
LOGOUT_REDIRECT_URL = 'match_list'

MESSAGE_TAGS = {
    message_constants.ERROR: 'danger',
}


# Email
# https://docs.djangoproject.com/en/6.1/topics/email/#topic-email-configuration

# Development: print emails (e.g. password reset) to the console.
EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'


# Logging
# https://docs.djangoproject.com/en/6.1/topics/logging/

# In development Django's built-in configuration already logs to the console.
# In production (DEBUG=False) that console handler is disabled and errors are
# routed to the unconfigured admin-email handler, so define a minimal
# stream configuration that writes to stderr instead. LOG_LEVEL is
# environment-configurable (e.g. LOG_LEVEL=DEBUG for a temporary deep dive).
if not DEBUG:
    LOGGING = {
        'version': 1,
        'disable_existing_loggers': False,
        'formatters': {
            'default': {
                'format': '{asctime} {levelname} {name}: {message}',
                'style': '{',
            },
        },
        'handlers': {
            'console': {
                'class': 'logging.StreamHandler',
                'formatter': 'default',
            },
        },
        'loggers': {
            'django': {
                'handlers': ['console'],
                'level': env('LOG_LEVEL', default='INFO'),
                'propagate': False,
            },
            'django.request': {
                'handlers': ['console'],
                'level': 'ERROR',
                'propagate': False,
            },
            'predictions': {
                'handlers': ['console'],
                'level': env('LOG_LEVEL', default='INFO'),
                'propagate': False,
            },
        },
    }
